<?xml version="1.0" encoding="UTF-8"?>
<definitions name="sinAplusB" targetNamespace="http://j2ee.netbeans.org/wsdl/sinAplusB"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/sinAplusB" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="sinAplusBOperationRequest">
        <part name="partA" type="xsd:double"/>
        <part name="partB" type="xsd:double"/>
    </message>
    <message name="sinAplusBOperationReply">
        <part name="FinalOut" type="xsd:double"/>
    </message>
    <portType name="sinAplusBPortType">
        <operation name="sinAplusBOperation">
            <input name="input1" message="tns:sinAplusBOperationRequest"/>
            <output name="output1" message="tns:sinAplusBOperationReply"/>
        </operation>
    </portType>
    <binding name="sinAplusBBinding" type="tns:sinAplusBPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="sinAplusBOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/sinAplusB"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/sinAplusB"/>
            </output>
        </operation>
    </binding>
    <service name="sinAplusBService">
        <port name="sinAplusBPort" binding="tns:sinAplusBBinding">
            <soap:address location="http://localhost:18181/sinAplusBService/sinAplusBPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="sinAplusB1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="sinAplusBPortTypeRole" portType="tns:sinAplusBPortType"/>
    </plnk:partnerLinkType>
</definitions>
