<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ArithmaticWebServiceServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ArithmaticWebServiceServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ArithmaticWebServiceServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://src/">
    <import location="ArithmaticWebServiceService.wsdl" namespace="http://src/"/>
    <plnk:partnerLinkType name="ArithmaticWebServiceLinkType">
        <plnk:role name="ArithmaticWebServiceRole" portType="ns:ArithmaticWebService"/>
    </plnk:partnerLinkType>
</definitions>
